// src/lib/provincias.ts

export const provincias = {
    comunidades: [
        { codigo: "01", nombre: "Andalucía" },
        { codigo: "02", nombre: "Aragón" },
        { codigo: "03", nombre: "Asturias, Principado de" },
        { codigo: "04", nombre: "Balears, Illes" },
        { codigo: "05", nombre: "Canarias" },
        { codigo: "06", nombre: "Cantabria" },
        { codigo: "07", nombre: "Castilla y León" },
        { codigo: "08", nombre: "Castilla - La Mancha" },
        { codigo: "09", nombre: "Cataluña" },
        { codigo: "10", nombre: "Comunitat Valenciana" },
        { codigo: "11", nombre: "Extremadura" },
        { codigo: "12", nombre: "Galicia" },
        { codigo: "13", nombre: "Madrid, Comunidad de" },
        { codigo: "14", nombre: "Murcia, Región de" },
        { codigo: "15", nombre: "Navarra, Comunidad Foral de" },
        { codigo: "16", nombre: "País Vasco" },
        { codigo: "17", nombre: "Rioja, La" },
        { codigo: "18", nombre: "Ceuta" },
        { codigo: "19", nombre: "Melilla" }
    ],
    provincias: [
        { codigo: "01", nombre: "Araba/Álava" },
        { codigo: "02", nombre: "Albacete" },
        { codigo: "03", nombre: "Alicante/Alacant" },
        { codigo: "04", nombre: "Almería" },
        { codigo: "05", nombre: "Ávila" },
        { codigo: "06", nombre: "Badajoz" },
        { codigo: "07", nombre: "Balears, Illes" },
        { codigo: "08", nombre: "Barcelona" },
        { codigo: "09", nombre: "Burgos" },
        { codigo: "10", nombre: "Cáceres" },
        { codigo: "11", nombre: "Cádiz" },
        { codigo: "12", nombre: "Castellón/Castelló" },
        { codigo: "13", nombre: "Ciudad Real" },
        { codigo: "14", nombre: "Córdoba" },
        { codigo: "15", nombre: "Coruña, A" },
        { codigo: "16", nombre: "Cuenca" },
        { codigo: "17", nombre: "Girona" },
        { codigo: "18", nombre: "Granada" },
        { codigo: "19", nombre: "Guadalajara" },
        { codigo: "20", nombre: "Gipuzkoa" },
        { codigo: "21", nombre: "Huelva" },
        { codigo: "22", nombre: "Huesca" },
        { codigo: "23", nombre: "Jaén" },
        { codigo: "24", nombre: "León" },
        { codigo: "25", nombre: "Lleida" },
        { codigo: "26", nombre: "Rioja, La" },
        { codigo: "27", nombre: "Lugo" },
        { codigo: "28", nombre: "Madrid" },
        { codigo: "29", nombre: "Málaga" },
        { codigo: "30", nombre: "Murcia" },
        { codigo: "31", nombre: "Navarra" },
        { codigo: "32", nombre: "Ourense" },
        { codigo: "33", nombre: "Asturias" },
        { codigo: "34", nombre: "Palencia" },
        { codigo: "35", nombre: "Palmas, Las" },
        { codigo: "36", nombre: "Pontevedra" },
        { codigo: "37", nombre: "Salamanca" },
        { codigo: "38", nombre: "Santa Cruz de Tenerife" },
        { codigo: "39", nombre: "Cantabria" },
        { codigo: "40", nombre: "Segovia" },
        { codigo: "41", nombre: "Sevilla" },
        { codigo: "42", nombre: "Soria" },
        { codigo: "43", nombre: "Tarragona" },
        { codigo: "44", nombre: "Teruel" },
        { codigo: "45", nombre: "Toledo" },
        { codigo: "46", nombre: "Valencia/València" },
        { codigo: "47", nombre: "Valladolid" },
        { codigo: "48", nombre: "Bizkaia" },
        { codigo: "49", nombre: "Zamora" },
        { codigo: "50", nombre: "Zaragoza" },
        { codigo: "51", nombre: "Ceuta" },
        { codigo: "52", nombre: "Melilla" }
    ]
}
